# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
#
proxy:
  https:
    enabled: true
 #   hosts:
 #     - my.entorn.io
 #   letsencrypt:
 #     contactEmail: orboan@ilg.cat
  # only the proxy's secretToken is required
  secretToken: c3a6b7b6c89839e448e5f85f30fcd51d521921a0d5e7ecbc55d2e5c098612648
  service:
    type: ClusterIP
singleuser:
  defaultUrl: "/lab"
  memory:
    limit: 4G
    guarantee: 4G
  cpu:
    limit: 4
    guarantee: 2
  uid: 0
  extraEnv:
    CHOWN_HOME: 'yes'
    CHOWN_HOME_OPTS: '-R'
    DOCKER_HOST: 'tcp://localhost:2375'
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
    SUDOERS_ALL: "true"
  storage:
    extraVolumes:
      - name: shm-volume
        emptyDir:
          medium: Memory
      - name: docker-sock-{username}
        emptyDir: {}
      - name: docker-data
        persistentVolumeClaim:
          claimName: dockerdata-claim
      - name: apps
        persistentVolumeClaim:
          claimName: apps-claim
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata-claim
      - name: conda-envs
        persistentVolumeClaim:
          claimName: conda-envs-claim
      - name: nbgrader-exchange
        persistentVolumeClaim:
          claimName: exchange-claim
    extraVolumeMounts:
      - name: shm-volume
        mountPath: /dev/shm
      - name: docker-data
        mountPath: /var/lib/docker
      - name: apps
        mountPath: /opt/apps
      - name: dbdata
        mountPath: /opt/dbdata
      - name: conda-envs
        mountPath: /opt/conda/envs
      - name: nbgrader-exchange
        mountPath: /usr/local/share/nbgrader/exchange 
      - name: docker-sock-{username}
        mountPath: /run
    homeMountPath: /home/{username}
    dynamic:
      storageClass: hostpath 
    capacity: 25Gi
  image:
    name: entorn-io/singleuser 
    tag: dev-0.1.0
    pullPolicy: IfNotPresent
  profileList:
    - display_name: "Entorn DEV"
      description: "Entorn de desenvolupament de programari"
      kubespawner_override:
        extra_containers:
          - name: docker
            image: entorn-io/dind:0.1.0
            imagePullPolicy: IfNotPresent
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ''
            securityContext: 
              privileged: true 
            volumeMounts: 
              - name: docker-data
                mountPath: /var/lib/docker 
              - name: volume-{username}
                mountPath: /home/{username}
              - name: docker-sock-{username}
                mountPath: /run
        security_context:
          privileged: true
          fsGroup: 100
    - display_name: "Entorn BIO"
      description: "Entorn de Data Science, BioInform√†tica i Big Data"
      kubespawner_override:
        image: entorn-io/singleuser:data-0.1.0
        extra_containers:
          - name: docker
            image: entorn-io/dind:0.1.0
            imagePullPolicy: IfNotPresent
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ''
            securityContext:
              privileged: true
            volumeMounts:
              - name: docker-data
                mountPath: /var/lib/docker
              - name: volume-{username}
                mountPath: /home/{username}
      security_context:
        privileged: true
        fsGroup: 100
    - display_name: "Entorn OPS"
      description: "Entorn bash, ansible, docker, jenkins"
      kubespawner_override:
        image: entorn-io/singleuser:ops-0.1.0
        extra_containers:
          - name: docker
            image: entorn-io/dind:0.1.0
            imagePullPolicy: IfNotPresent
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ''
            securityContext:
              privileged: true
            volumeMounts:
              - name: docker-data
                mountPath: /var/lib/docker
              - name: volume-{username}
                mountPath: /home/{username}
      security_context:
        privileged: true
        fsGroup: 100          
hub:
  image:
    name: entorn-io/hub
    tag: 0.1.0
    pullPolicy: IfNotPresent
  config:
    extraEnv:
      LTI_AUTH_CONSUMER_URL: 'https://educaciodigital.cat'
      #    DummyAuthenticator:
      #      password: pluralcamp
      #    JupyterHub:
      #      authenticator_class: dummy
      #    Authenticator:
      #      admin_users:
      #        - orboan
  extraConfig:
    lti-auth: |
      c.JupyterHub.authenticator_class = MyLTIAuthenticator
    spawner: |
      c.Spawner.cmd = ['start.sh','jupyterhub-singleuser','--allow-root']
      def notebook_dir_hook(spawner):
          is_instructor='false'
          for instructor in instructors:
              f = open("/home/entorn/instructor.out", "a")
              f.write(f"spawner.user.name = {spawner.user.name} - instructor id = {instructor['id']}")
              f.close()
              if spawner.user.name == instructor['id']:
                  is_instructor='true'
                  break
          spawner.environment = {'NB_USER':spawner.user.name,'NB_UID':'1000','IS_INSTRUCTOR':is_instructor, 'CHOWN_HOME':'yes', 'CHOWN_HOME_OPTS':'-R', 'DOCKER_HOST':'tcp://localhost:2375', 'GRANT_SUDO':"yes",'NOTEBOOK_ARGS':"--allow-root", 'SUDOERS_ALL': "true"}
      c.Spawner.pre_spawn_hook = notebook_dir_hook
    security: |
      from kubernetes_asyncio import client
      def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
      c.JupyterHub.admin_access = True
    cull:
      timeout=3800
ingress:
  enabled: true
  hosts:
    - local.entorn.io
    #- host: local.entorn.io
    #  paths:
    #    - path: /
    #      pathType: Prefix
    #      backend:
    #        serviceName: $name 
    #        servicePort: 8888
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-port-in-redirects: "false"
    nginx.ingress.kubernetes.io/healthcheck-port: '8443'
    nginx.ingress.kubernetes.io/ssl-redirect: '443'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      set $user 'user-redirect';
      #rstudio
      if ( $http_referer ~ ".*user\/(?<user_id>[\w-\.\w-]+)\/lab$" ) {
            rewrite ^/(?<arg_suffix>auth-sign-in.*) "https://$server_name/user/$user_id/rstudio/$arg_suffix";
      }      
      ## jetty
      if ( $http_referer ~ ".*user\/(?<user_id>[\w\-\.\w\-]+)\/jetty\/.*$" ) {
        rewrite ^/hub/(?<arg_suffix>.*) "https://$server_name/user/$user_id/jetty/${arg_suffix}" break;
      }
      ## jenkins
      if ( $http_referer ~ ".*user\/(?<user_id>[\w\-\.\w\-]+)\/jenkins\/.*$" ) {
        rewrite ^/hub/(?<arg_suffix>.*) "https://$server_name/user/$user_id/jenkins/${arg_suffix}" break;
      }
      ### pgadmin
      set $pg 0;
      if ($http_referer ~ ".*user\/(?<user_id>[\w\-\.\w\-]+)\/pgadmin\/.*$") {
        set $pg 1;
        set $user $user_id;
      }
      if ($request_uri ~ ".*user\/(?<user_id>[\w\-\.\w\-]+)\/pgadmin\/.*$") {
        set $pg 1;
        set $user $user_id;
      }
      if ($pg = 1) {
        rewrite ^/hub/(?<arg_suffix>.*) "https://$server_name/user/$user_id/pgadmin/${arg_suffix}" break;
      }

      proxy_hide_header Allow;
      proxy_hide_header X-Frame-Options;
      proxy_hide_header Content-Security-Policy;
      proxy_hide_header X-XSS-Protection;
      proxy_hide_header X-Content-Type-Options;

      if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        #
        # Custom headers and headers various browsers *should* be OK with but aren't
        #
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        #
        # Tell client that this pre-flight info is valid for 20 days
        #
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        add_header 'Allow' 'GET, POST, OPTIONS' always;
        add_header 'X-Frame-Options' '""' always;
        return 204;
      }
      if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        add_header 'Allow' 'GET, POST, OPTIONS' always;
        add_header 'X-Frame-Options' '""' always;
      }
      if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
        add_header 'Allow' 'GET, POST, OPTIONS' always;
        add_header 'X-Frame-Options' '""' always;
      }

      proxy_set_header X-Script-Name /user/$user/pgadmin;
